# Generated by Django 5.2.3 on 2025-07-03 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(max_length=25)),
                ('busnumber', models.IntegerField(unique=True)),
                ('source', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=20)),
                ('departure', models.CharField(max_length=100)),
                ('arrival', models.CharField(max_length=100)),
                ('departuretime', models.TimeField()),
                ('arrivaltime', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.DurationField()),
                ('available_seats', models.IntegerField()),
                ('type', models.CharField(choices=[('AC', 'AC'), ('NONAC', 'Non-AC')], max_length=5)),
            ],
        ),
    ]
