# Generated by Django 5.2.3 on 2025-07-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='duration',
            field=models.TimeField(),
        ),
    ]
