# Generated by Django 5.2.3 on 2025-07-07 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0002_alter_buses_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date_TOB', models.DateTimeField(auto_now_add=True)),
                ('no_of_seats', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.BigIntegerField(default='temporary')),
                ('email', models.EmailField(default='temporary', max_length=254)),
                ('pincode', models.IntegerField(default='temporary')),
                ('city', models.CharField(default='temporary', max_length=50)),
                ('state', models.CharField(default='temporary', max_length=50)),
                ('address', models.CharField(default='temporary', max_length=200)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='Buses.buses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeatsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('age', models.IntegerField()),
                ('seat', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seatDetail', to='Buses.bookings')),
            ],
        ),
    ]
