# Generated by Django 5.2.3 on 2025-07-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0003_bookings_seatsdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='contact',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
