# Generated by Django 5.2.3 on 2025-07-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0004_alter_bookings_address_alter_bookings_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='price',
        ),
    ]
