# Generated by Django 5.2.3 on 2025-07-07 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0005_remove_bookings_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatsdetail',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
