# Generated by Django 5.2.3 on 2025-07-07 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Buses', '0006_rename_booking_id_seatsdetail_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='booking_id',
            new_name='id',
        ),
    ]
